### ISSUE TITLE
[FEATURE] Add version of `fill` that accepts UIEdgeInsets

### ISSUE THREAD

**Issue by g-mark** [ww-tech/wwlayout#28]
The `fill` functions accept `CGFloat` or `Insets` values, and another version should be added that accepts a `UIEdgeInsets` - especially since it is directly convertible to `Insets`.

**Comment by Osein** [comment]
Anybody have progress in this? I am planning to start contributing with this.

**Comment by g-mark** [comment]
Thanks for taking this on, @Osein
